pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Tools') {
            steps {
                bat 'git --version'
                bat 'python --version'
                bat 'pip --version'
                bat 'where python'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'python -m pip install --upgrade pip'
                bat 'pip install -r requirements.txt'
            }
        }

        stage('Run Tests + Coverage') {
            steps {
                bat 'if not exist reports mkdir reports'
                bat 'coverage run -m pytest --junitxml=reports\\junit.xml'
                bat 'coverage xml -o reports\\coverage.xml'
                bat 'coverage report'
            }
        }

        stage('Package Artifact') {
            steps {
                bat 'powershell -Command "Compress-Archive -Path *.py -DestinationPath math_utils_artifact.zip -Force"'
            }
        }
    }

    post {
        always {
            // publish unit test results in Jenkins
            junit 'reports/junit.xml'

            // save reports + zip as build artifacts
            archiveArtifacts artifacts: 'reports/**, math_utils_artifact.zip', fingerprint: true
        }
    }
}
